{{- if .Values.httpRoute.enabled }}
{{- $fullName := include "generic.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
    {{- with .Values.httpRoute.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  rules:
  {{- range .Values.httpRoute.rules }}
  - backendRefs:
    - name: "{{ $fullName }}"
      port: {{ .port | default $svcPort }}
    matches:
      {{- with .matches }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
    {{- if .filters }}
    {{- with .filters }}
    filters:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
